Add indexers to flotta resources
project-flotta/flotta-operator pull request #134
Opened 2022-03-13 23:01 UTC by masayag

Adding indexers on flotta's CR cache.
In addition, added namespace scope for edgedeployment.ListByLabel
which is the most CPU consuming function.

Signed-off-by: Moti Asayag <masayag@redhat.com>

2022-03-14 07:41 UTC, jakub-dzon commented on main.go
> +		//ClientDisableCacheFor:
This should be removed in the final version of the PR.

2022-03-17 07:49 UTC, jakub-dzon approved these changes

2022-03-17 08:22 UTC, eloycoto requested changes

2022-03-17 08:22 UTC, eloycoto commented on internal/repository/indexer.go
> +func DeploymentByDeviceIndexFunc(obj ctrlruntimeclient.Object) []string {
As critical these functions are, should be tested, no?

2022-03-17 16:06 UTC, eloycoto approved these changes

2022-03-17 16:06 UTC, merged