Pass deployment namespace as workload namespace
project-flotta/flotta-operator pull request #140
Opened 2022-03-16 15:07 UTC by machacekondra

This commit add a new parameter namespace to workload model type, which
define the namespace of the deployment and should be used to distinguish
the workload on device-worker side.

Signed-off-by: Ondra Machacek <omachace@redhat.com>

2022-03-16 15:26 UTC, eloycoto requested changes
and an open question, what happens if a workload is deployed in a different namespace of the device?

2022-03-16 15:26 UTC, eloycoto commented on internal/yggdrasil/yggdrasil.go
> +			Namespace:     deployment.Namespace,
I'm happy with the change, but I think that it'll be good to add at least one assert on the integration test :-)

2022-03-17 10:23 UTC, machacekondra commented
> and an open question, what happens if a workload is deployed in a different namespace of the device?

Currently it's not deployed at all if I am not mistaken.

2022-03-17 12:52 UTC, eloycoto approved these changes

2022-03-17 14:29 UTC, pkliczewski approved these changes

2022-03-17 18:40 UTC, masayag approved these changes

2022-03-17 18:40 UTC, merged