Rename `edgeDeployment` to `edgeWorkload`
project-flotta/flotta-operator pull request #175
Opened 2022-04-04 19:43 UTC by arielireni

Renamed `edgeDeployment` to `edgeWorkload` in order to avoid confusing with k8s deployment.

Signed-off-by: arielireni <aireni@redhat.com>

2022-04-07 08:40 UTC, machacekondra commented on config/rbac/role.yaml
> +- apiGroups:
I think you can remove this, it's already on line 36

2022-04-07 16:18 UTC, masayag approved these changes

2022-04-08 06:24 UTC, machacekondra approved these changes

2022-04-08 08:57 UTC, jakub-dzon requested changes

2022-04-08 08:57 UTC, jakub-dzon commented on docs/design/architecture.puml
> -'https://plantuml.com/deployment-diagram
That should not be changed to `workload`

2022-04-08 08:57 UTC, jakub-dzon commented on docs/osLifecycle.puml
> -'https://plantuml.com/deployment-diagram
URL should remain unchanged.

2022-04-11 06:30 UTC, jakub-dzon approved these changes

2022-04-11 06:31 UTC, merged