Agent installation adding port option
project-flotta/flotta-operator pull request #212
Opened 2022-05-09 15:17 UTC by eloycoto

When running agent script always uses port 8043, with this patch port
8043 is set by default, but you can run with a specific argument:

```
$ hack/install-agent-dnf.sh -i 192.168.2.10 -p 443
```

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>

2022-05-09 15:31 UTC, gabriel-farache requested changes

2022-05-09 15:31 UTC, gabriel-farache commented on hack/install-agent-dnf.sh.template
>             kubectl port-forward service/flotta-operator-controller-manager -n flotta 8043 --address 0.0.0.0
change `8043` by `<FLOTTA_PORT>` or something like that to emphasis that the provided port should be used. Or add `ie: ` before the command to be clear that it's a simple example using default values.
Also, change [this](https://github.com/project-flotta/flotta-operator/blob/feb03938c5fd901b2db04904d01375735d4e3919/hack/install-agent-dnf.sh.template#L10) that describe `-i` option

2022-05-09 15:31 UTC, gabriel-farache commented on hack/install-agent-rpm-ostree.sh.template
>             kubectl port-forward service/flotta-operator-controller-manager -n flotta 8043 --address 0.0.0.0
change 8043 by <FLOTTA_PORT> or something like that to emphasis that the provided port should be used. Or add ie: before the command to be clear that it's a simple example using default values.
Also, change [this](https://github.com/project-flotta/flotta-operator/blob/feb03938c5fd901b2db04904d01375735d4e3919/hack/install-agent-rpm-ostree.sh.template#L10) that describe -i option

2022-05-10 11:56 UTC, gabriel-farache approved these changes

2022-05-10 12:06 UTC, masayag approved these changes

2022-05-10 12:06 UTC, merged